# Generated by Django 5.2.6 on 2025-10-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado', max_digits=5),
        ),
    ]
