# Generated by Django 5.2.6 on 2025-10-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0002_ordencompra_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
