# Generated by Django 5.2.6 on 2025-10-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COTIFAC', '0003_alter_ordencompra_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
