# Generated by Django 5.2.6 on 2025-09-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=200)),
                ('vendedor', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle_items', models.TextField(help_text='Ej: 2 x Producto A - $1000\n1 x Producto B - $500')),
            ],
        ),
    ]
