# Generated by Django 5.2.6 on 2025-10-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDEXA', '0003_ordencompra_estado_ordencompra_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='vendedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
